version: '2'
services:
    whatandwhere-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/WhatAndWhere/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=WhatAndWhere
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
